"""TableEmployees

Revision ID: 1a2a54aeb29c
Revises: 4598bbce3cf0
Create Date: 2026-08-11 09:19:29.600897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2a54aeb29c'
down_revision: Union[str, Sequence[str], None] = '4598bbce3cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('title', sa.Enum('PM', 'DEV', name='title'), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('assign_to_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'employees', ['assign_to_id'], ['id'])
    op.drop_column('tasks', 'attribution_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('attribution_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assign_to_id')
    op.drop_table('employees')
    # ### end Alembic commands ###
