"""Add Photo

Revision ID: 20a97cfbe40a
Revises: b09cb1cb7097
Create Date: 2026-08-13 09:06:24.317559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a97cfbe40a'
down_revision: Union[str, Sequence[str], None] = 'b09cb1cb7097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'photo')
    # ### end Alembic commands ###
